# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appservice-rg-terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrtodorgterraform.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5ed5fc7880d240669cd295f5ea9d5256 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1707080a97dc40398c84311ac9d476f3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrtodorgterraform.azurecr.io/mytodoapi_5ed5fc7880d240669cd295f5ea9d5256/todoapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appservice-rg-terraform'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_43bcc3b09e3545c6b9e7d74b4bfdecfd }}
        images: 'acrtodorgterraform.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5ed5fc7880d240669cd295f5ea9d5256 }}/todoapi:${{ github.sha }}'
